Init branch PR - Első feladat elkészült
Teaching-projects/SZE-MOSZE-2020-Runtime_Terror pull request #1
Opened 2020-09-14 07:48 UTC by tamastomordi

Elkészültünk az első kiírt feladattal:
* két egység csapkodja egymást, amíg egyik meg nem hal
* README.md szerkesztve

2020-09-15 14:07 UTC, hegyhati requested changes

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +class Unit {
TEssek kulon fajlba kirakni.

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +    int damage{};
const? illetve minek a `{}`?

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +        return (health <= 0) ? true : false;
na, ennek fusunk neki meg egyszer. Illetve const?

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +    }
but why?

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +    void Attack(Unit &target) {
const?

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +class Game {
nem szukseges, de ha marad, akkor kulon fajlba.

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +        this->player = Unit(data[1], stoi(data[2]), stoi(data[3]));
minek a this?

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +    void PrintCurrentState() {
const?

2020-09-15 14:07 UTC, hegyhati commented on main.cpp
> +    Game game = Game(data);
kicsit overcomplicated, de elmegy.

2020-09-16 11:00 UTC, tamastomordi commented on main.cpp
> +class Unit {
Kiraktam külön fájlba.

2020-09-16 11:01 UTC, tamastomordi commented on main.cpp
> +    }
Törölve.

2020-09-16 11:01 UTC, tamastomordi commented on main.cpp
> +class Game {
Meghagytuk. Átraktam külön fájlba.

2020-09-16 11:01 UTC, tamastomordi commented on main.cpp
> +        this->player = Unit(data[1], stoi(data[2]), stoi(data[3]));
Törölve.

2020-09-16 11:04 UTC, Jabezare commented on main.cpp
> +    int damage{};
Name és damage const, a health változik, így meghagytuk. Felesleges zárójelek törölve.

2020-09-16 11:05 UTC, Jabezare commented on main.cpp
> +    void Attack(Unit &target) {
Megcsináltam const-ra.

2020-09-16 11:05 UTC, Jabezare commented on main.cpp
> +    void PrintCurrentState() {
Const-ra megcsinálva.

2020-09-16 11:06 UTC, Jabezare commented on main.cpp
> +    Game game = Game(data);
Leegyszerűsítettük.

2020-09-16 13:09 UTC, tamastomordi commented on main.cpp
> +        return (health <= 0) ? true : false;
Átírtam és const-ra raktam. Nem vagyok benne biztos, de talán így most jó...

2020-09-16 13:11 UTC, tamastomordi commented
@hegyhati Megcsináltuk a kért módosításokat.

2020-09-16 23:09 UTC, hegyhati requested changes
const-oknak tessek kicsit utananezni.

2020-09-16 23:09 UTC, hegyhati commented on Game.cpp
> +const void Game::SimulateTurn(Unit &attacker, Unit &target) {
const void? nani?

2020-09-16 23:09 UTC, hegyhati commented on Game.cpp
> +const void Game::SimulateTurn(Unit &attacker, Unit &target) {
az attacker mondjuk lehetne const.

2020-09-16 23:09 UTC, hegyhati commented on Game.cpp
> +const void Game::Combat() {
ezt a const voidot tenyleg nem tudom, honnet szedtetek :-D

2020-09-16 23:09 UTC, hegyhati commented on Game.cpp
> +const void Game::PrintCurrentState() {
ez megintcsak lehetne const. de nem a visszateresi erteke.

2020-09-16 23:09 UTC, hegyhati commented on Game.h
> +    Unit enemy;
azert ezeket lehet inkabb privatba tennem.

2020-09-16 23:09 UTC, hegyhati commented on Unit.h
> +};
ugyanaz. tessek atnezni, mire hol kell const, es mit illik privatba tenni.

2020-09-17 18:57 UTC, tamastomordi commented
@hegyhati Nekifutottunk még egyszer, talán így már jobb lesz.

2020-09-18 09:15 UTC, hegyhati requested changes
Par aprosag mar csak.

2020-09-18 09:15 UTC, hegyhati commented on Game.cpp
> +Game::Game(const Unit player, const Unit enemy) : player(player), enemy(enemy)
szandekosan csinaltok masolatot?

2020-09-18 09:15 UTC, hegyhati commented on Unit.h
> +    const int damage;
ezek menjenek privatba

2020-09-18 09:15 UTC, hegyhati commented on Game.cpp
> +Game::Game(const Unit player, const Unit enemy) : player(player), enemy(enemy)
Marmint nem az inicializalasnal, hanem az argumentumoknal.

2020-09-18 09:15 UTC, hegyhati commented on main.cpp
> +    /* game.Combat() */
overkill kicsit, de maradhat igy, ez a komment akkor keruljon ki.

2020-09-18 12:59 UTC, tamastomordi commented on Unit.h
> +    const int damage;
Átraktam őket privátba, viszont így csinálnom kellett getter-eket, hogy elérjük az adatokat a Game osztályból, gondolom ez nem probléma. Illetve csináltam egy plusz SufferDamage metódust ami leviszi az adott Unit életét.

2020-09-18 13:00 UTC, tamastomordi commented on main.cpp
> +    /* game.Combat() */
Kommentek eltávolítva.

2020-09-18 13:11 UTC, tamastomordi commented on Game.cpp
> +Game::Game(const Unit player, const Unit enemy) : player(player), enemy(enemy)
Nem szándékos volt. Javítottam.

2020-09-18 13:12 UTC, tamastomordi commented
@hegyhati Kért módosítások megcsinálva.

2020-09-21 13:49 UTC, hegyhati approved these changes

2020-09-21 13:49 UTC, merged