Makefile
Teaching-projects/SZE-MOSZE-2020-Runtime_Terror pull request #10
Opened 2020-10-30 16:30 UTC by Jabezare

@hegyhati Elkészültem a makefile feladatrésszel.

2020-10-31 19:21 UTC, hegyhati requested changes

2020-10-31 19:21 UTC, hegyhati commented on Makefile
> +
A player nem dependel a unit-ra?

2020-10-31 19:21 UTC, hegyhati commented on Makefile
> +
Meg a JSON-re?

2020-10-31 19:21 UTC, hegyhati commented on Makefile
> +	bash -c "./test.sh"
miert bash -c-zel?

2020-11-01 11:19 UTC, Jabezare commented
@hegyhati Javítottam a hibákat és hiányosságokat.

2020-11-02 00:14 UTC, hegyhati approved these changes
Conflictokat oldd fel, aztan mehet be.

2020-11-02 11:49 UTC, merged