Light radius
Teaching-projects/SZE-MOSZE-2020-Runtime_Terror pull request #21
Opened 2020-12-02 08:27 UTC by tamastomordi

Light radius added.
Frame added to the map.

2020-12-02 21:16 UTC, bencebaranyai requested changes

2020-12-02 21:16 UTC, bencebaranyai commented on Game.cpp
> +            for(int i = 0; i < 2*hero->getLightRadius()+1; i++) std::cout << "══";
A limitet ellenőrizni kellene, mert 2-nél működik, de amint nagyobb értékkel rendelkezik a `LightRadius` elcsúszik a keret. (Alsó keret is, egyébként jó)

2020-12-03 13:12 UTC, bencebaranyai approved these changes

2020-12-03 13:17 UTC, Jabezare approved these changes

2020-12-03 13:19 UTC, csibe1999 approved these changes

2020-12-03 13:22 UTC, merged