Levelup
Teaching-projects/SZE-MOSZE-2020-Runtime_Terror pull request #4
Opened 2020-10-13 16:59 UTC by tamastomordi

@hegyhati Elkészültem a levelup branch-el.

2020-10-17 10:50 UTC, oliverosz requested changes
A szintlépés kezelése jó. A `Game` osztály új változata nem tetszik, azt refaktoráljátok valami értelmesebbre.
Ha ez megvan, akkor frissítsétek a branchet a masterre, és javítsátok ki a conflictokat.

2020-10-17 10:50 UTC, oliverosz commented on .github/workflows/test.yml
> +      - run: cppcheck --enable=all --error-exitcode=1 *.cpp 2> static-code-analysis.txt
Így nem fog soha semmi hibát artifactolni, mert ha bármi hibát talál, akkor az exit-code leállítja a workflow-t. Legyen egy külön ellenőrzés, ami csak warning szintet néz, és errort dob, meg egy másik, amiben mindent vizsgál, de nem dob errort, csak artifactol.

2020-10-17 10:50 UTC, oliverosz commented on .github/workflows/test.yml
> +      - run: valgrind --error-exitcode=1 ./a.out unit1.json unit2.json 2> ./memory-leak-check.txt
A valgrindnak még egy `--leak-check=full` opciót is meg kell adni, különben nem minden hibát tekint errornak.

2020-10-17 10:50 UTC, oliverosz commented on Game.h
> -    Unit enemy;
Ha már nincsenek tárolva a harcosok, akkor ennek az osztálynak így nem sok értelme van, a metódusok akár statikusak is lehetnek. Ez így inkább csak egy namespace. Ami nem baj, de akkor ez látszódjon az interfészből: legyenek statkusak azok a függvények, vagy csináljatok egy namespace-t az osztályból.

2020-10-17 10:50 UTC, oliverosz commented on Game.h
> -    Unit enemy;
De ha referenciákat (`Unit&`) tárolna, az is jó megoldás lenne, elvégre ez a polimorfizmus lényege. Most ez az osztály nem használja ki, hogy a Player is Unit.

2020-10-17 10:50 UTC, oliverosz commented on Player.cpp
> +     maxHealth = health;
inicializáló listába vele

2020-10-17 17:34 UTC, tamastomordi commented
@oliverosz A kért módosítások megcsinálva és az ütközések feloldva!

2020-10-18 19:01 UTC, oliverosz approved these changes

2020-10-18 19:02 UTC, merged