Jsonparser
Teaching-projects/SZE-MOSZE-2020-Runtime_Terror pull request #6
Opened 2020-10-15 17:50 UTC by csibe1999

@wajzy Elkészült a JsonParser és hozzá a tesztek is.

2020-10-18 16:47 UTC, wajzy requested changes
Fel kellene készíteni a parzert legalább néhány, könnyen elkövethető hiba felderítésére, és kezelésére. Pl. mit történik, ha kifelejtjük a :-ot? Utána persze tesztesetre is szükség lenne, hogy lássuk, tényleg jól működik-e a parzer.

2020-10-18 16:47 UTC, wajzy commented on Json.cpp
> +    }
Hűha, ez bátor. Ha jól értem, amennyiben valakinek a neve szóközt tartalmaz, akkor most jól átnevezzük.

2020-10-19 13:55 UTC, csibe1999 commented on Json.cpp
> +    }
@wajzy A kért változtatásokat megcsináltam.

2020-10-20 13:33 UTC, wajzy approved these changes
OK, elfogadom, mert látszik, hogy foglalkoztál a továbbfejlesztéssel. Legalább a két függvényt azért tedd át kérlek private/protected-be.

2020-10-20 13:33 UTC, wajzy commented on Json.cpp
> +    std::string trimmedtext = text.substr(first, last - first + 1);
Nem fog ez kivételt dobni, ha first értéke npos?

2020-10-20 13:33 UTC, wajzy commented on Json.h
> +    static std::string Trim(const std::string &text);
Én ezeket elrejteném a külvilág elől.

2020-10-20 13:34 UTC, wajzy commented
@csibe1999 Majd oldd fel az ütközéseket is, légy szíves!

2020-10-24 13:59 UTC, wajzy approved these changes
OK

2020-10-24 13:59 UTC, merged