Added more unit test
Teaching-projects/SZE-MOSZE-2020-Runtime_Terror pull request #8
Opened 2020-10-30 15:04 UTC by csibe1999

2020-10-30 15:36 UTC, karcagtamas requested changes

2020-10-30 15:36 UTC, karcagtamas commented on test/Tester.cpp
> +TEST(PlayerTest, Player)
Szerintem a Player-rel kapcsolatots tesztek kerülhetnének külön fájlba, a jobb átláthatóság végett.

2020-10-30 15:36 UTC, karcagtamas commented on test/Tester.cpp
> +    ASSERT_THROW(Unit::parseUnit("doesntexits.json"), std::runtime_error);
Ez kerülhetnek külön test case-be

2020-10-30 15:36 UTC, karcagtamas commented on test/Tester.cpp
> +    ASSERT_THROW(Unit::parseUnit("doesntexits.json"), std::runtime_error);
Késöbb láttam, hogy ez a teszt eset már létezik. (59. sor)

2020-10-30 15:36 UTC, karcagtamas commented on test/Tester.cpp
> +    ASSERT_NO_THROW(Unit::parseUnit("../unit/unit1.json"));
Létezik máshol is. (60. sor)

2020-10-30 15:36 UTC, karcagtamas commented on Json.cpp
> +    if (mapedData.size() != 4)
Annak `mappedData`-nak kéne lennie.

2020-10-30 15:36 UTC, karcagtamas commented on Json.cpp
> +        if (isdigit(token[1]))
Szerintem ha a például egy ilyen szöveg kerül a token változújába: "12 körte", akkor utána a stof(token) elfog hasalni.
Cáfolj meg ha nem így van.

2020-10-30 15:36 UTC, karcagtamas commented on Json.cpp
> +    if (mapedData.size() != 4)
Ha a map nem négy elemet tartalmaz, akkor miért invalid a Json? 
Tudnia kell beolvasni kisebb és nagyobb JSON fájlokat is.

2020-11-01 13:11 UTC, karcagtamas requested changes
Még egy apróságot találtam

2020-11-01 13:11 UTC, karcagtamas commented on test/jsonTester.cpp
> +    ASSERT_THROW(Json::ParseString("{    \"name\" : \"Kakarott\",    \"hp\" : 200    dmg\" : 90, \"attackcooldown\": 1.0  }"), std::runtime_error);
Adhatnál még ide egy két olyan teszt esetet ahol, nem csak egy szükséges karakter hiányzik, hanem több is.
Pl: hiányzik két idéző jel, vagy kettőspont és és kapcsos zárójel.

2020-11-01 15:12 UTC, karcagtamas approved these changes
Szuper

2020-11-01 18:10 UTC, bencebaranyai requested changes

2020-11-01 18:10 UTC, bencebaranyai commented on test/Tester.cpp
> +    return RUN_ALL_TESTS();
A unit tesztekkel kapcsolatban keresem a workflowt, de nem találom.

Ezt pótolni kéne, mivel még az előző feladat része volt (#6) és továbbra is futnia kellene.

2020-11-02 13:19 UTC, karcagtamas requested changes

2020-11-02 13:19 UTC, karcagtamas commented on .github/workflows/tester.yml
> +      - unittests
Az össze többi (főleg jövőbeli) branchen is futnia kell a workflow-nak.

2020-11-02 13:24 UTC, karcagtamas approved these changes

2020-11-02 16:35 UTC, bencebaranyai approved these changes

2020-11-03 09:20 UTC, tamastomordi approved these changes

2020-11-03 09:30 UTC, Jabezare approved these changes

2020-11-03 19:19 UTC, merged