Documentation
Teaching-projects/SZE-MOSZE-2020-Runtime_Terror pull request #9
Opened 2020-10-30 15:10 UTC by tamastomordi

Elkészült a dokumentáció a másik két osztályhoz is.

2020-10-30 15:42 UTC, karcagtamas requested changes

2020-10-30 15:42 UTC, karcagtamas commented on .github/workflows/pushdocs.yml
> +      - documentation
Ez merge után megint felesleges lesz.

2020-10-30 15:42 UTC, karcagtamas commented on Player.h
> + * \brief Player class inherited from Unit class
A megjegyzés jó, csak szerintem lehetne részletesebben fejtegetni a Player tartalmát, mire való az osztály, mit kezel, mi történik benne, stb.

2020-10-30 15:42 UTC, karcagtamas commented on Game.h
>   * \brief Game class
Részletesebben leírás szükséges az osztályhoz.

2020-10-30 15:42 UTC, karcagtamas commented on Json.h
> + * \brief Json Parser class containing static functions
Részletesebben leírás szükséges az osztályhoz.

2020-11-01 10:22 UTC, tamastomordi commented
@karcagtamas A kért módosítások elvégezve.

2020-11-01 10:26 UTC, karcagtamas approved these changes

2020-11-01 10:29 UTC, karcagtamas commented
Approvoltam, de mivel nincs write hozzáférésem így nem ér sokat. 
@hegyhati

2020-11-01 13:05 UTC, bencebaranyai approved these changes

2020-11-01 14:12 UTC, Cerberuuus approved these changes

2020-11-01 14:41 UTC, csibe1999 approved these changes

2020-11-01 14:43 UTC, Jabezare approved these changes

2020-11-02 00:13 UTC, hegyhati commented
Itt most nem latom a kommentet, lehet torolve lett, de: 
![image](https://user-images.githubusercontent.com/13832329/97819391-91bb8080-1ca8-11eb-83b7-9bf7c14ab238.png)
Es a conflictokat majd nyilvan oldjatok fel.

2020-11-02 10:09 UTC, merged